include:
  - docker-compose.yml

services:
  # 应用部署相关
  healwrap-monitor-server:
    image: bitnami/node:latest
    container_name: healwrap-monitor-server
    ports:
      - 8081:8081
    volumes:
      - ../:/app/monitor
    environment:
      - NODE_ENV=production
    working_dir: /app/monitor/apps/backend/monitor
    command: 'node dist/main.js'
    depends_on:
      - healwrap-monitor-postgresql
      - healwrap-monitor-redis
      - healwrap-monitor-clickhouse
    #   - healwrap-monitor-kafka
  healwrap-monitor-caddy:
    image: caddy:latest
    container_name: healwrap-monitor-caddy
    ports:
      - 82:80
      - 444:443
      - 444:443/udp
    volumes:
      - ./caddy:/etc/caddy
      - ../apps/frontend/monitor/dist:/app/frontend/monitor/dist
